use std::error;

pub fn main() -> Result<(), Box<dyn error::Error>> {
    println!("Running with std");

    Ok(())
}
